# Generated by Django 3.0.3 on 2020-02-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='last_time',
            new_name='last_active',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
